# add_executable(sgemm_v0 "sgemm_v0.cu")
# target_link_libraries(sgemm_v0 MPI::MPI_CXX CUDA::cudart CUDA::cublas)
# if(CMAKE_BUILD_TYPE STREQUAL "Debug")
#     target_compile_options(sgemm_v0 PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:-G>)
# endif()

# add_executable(sgemm_v1 "sgemm_v1.cu")
# target_link_libraries(sgemm_v1 MPI::MPI_CXX CUDA::cudart CUDA::cublas)
# if(CMAKE_BUILD_TYPE STREQUAL "Debug")
#     target_compile_options(sgemm_v1 PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:-G>)
# endif()

# add_executable(sgemm_v2 "sgemm_v2.cu")
# target_link_libraries(sgemm_v2 MPI::MPI_CXX CUDA::cudart CUDA::cublas)
# if(CMAKE_BUILD_TYPE STREQUAL "Debug")
#     target_compile_options(sgemm_v2 PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:-G>)
# endif()

# add_executable(sgemm_v3 "sgemm_v3.cu")
# target_link_libraries(sgemm_v3 MPI::MPI_CXX CUDA::cudart CUDA::cublas)
# if(CMAKE_BUILD_TYPE STREQUAL "Debug")
#     target_compile_options(sgemm_v3 PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:-G>)
# endif()

# add_executable(sgemm_v4 "sgemm_v4.cu")
# target_link_libraries(sgemm_v4 MPI::MPI_CXX CUDA::cudart CUDA::cublas)
# if(CMAKE_BUILD_TYPE STREQUAL "Debug")
#     target_compile_options(sgemm_v4 PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:-G>)
# endif()

# add_executable(sgemm_v5 "sgemm_v5.cu")
# target_link_libraries(sgemm_v5 MPI::MPI_CXX CUDA::cudart CUDA::cublas)
# if(CMAKE_BUILD_TYPE STREQUAL "Debug")
#     target_compile_options(sgemm_v5 PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:-G>)
# endif()

# add_executable(sgemm_v5_6 "sgemm_v5_6.cu")
# target_link_libraries(sgemm_v5_6 MPI::MPI_CXX CUDA::cudart CUDA::cublas)
# if(CMAKE_BUILD_TYPE STREQUAL "Debug")
#     target_compile_options(sgemm_v5_6 PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:-G>)
# endif()

# add_executable(sgemm_v6 "sgemm_v6.cu")
# target_link_libraries(sgemm_v6 MPI::MPI_CXX CUDA::cudart CUDA::cublas)
# if(CMAKE_BUILD_TYPE STREQUAL "Debug")
#     target_compile_options(sgemm_v6 PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:-G>)
# endif()

# add_executable(sgemm_v7 "sgemm_v7.cu")
# target_link_libraries(sgemm_v7 MPI::MPI_CXX CUDA::cudart CUDA::cublas)
# if(CMAKE_BUILD_TYPE STREQUAL "Debug")
#     target_compile_options(sgemm_v7 PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:-G>)
# endif()

add_executable(test_frame "test_frame.cu")
target_link_libraries(test_frame MPI::MPI_CXX CUDA::cudart CUDA::cublas)
# if(CMAKE_BUILD_TYPE STREQUAL "Debug")
#     target_compile_options(test_frame PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:-G>)
# endif()

