
# add_executable(reduce_v0 "reduce_v0.cu")
# target_link_libraries(reduce_v0 MPI::MPI_CXX CUDA::cudart)

# add_executable(reduce_v1 "reduce_v1.cu")
# target_link_libraries(reduce_v1 MPI::MPI_CXX CUDA::cudart)

# add_executable(reduce_v2 "reduce_v2.cu")
# target_link_libraries(reduce_v2 MPI::MPI_CXX CUDA::cudart)

# add_executable(reduce_v3 "reduce_v3.cu")
# target_link_libraries(reduce_v3 MPI::MPI_CXX CUDA::cudart)

# add_executable(reduce_v4 "reduce_v4.cu")
# target_link_libraries(reduce_v4 MPI::MPI_CXX CUDA::cudart)

# add_executable(reduce_v5 "reduce_v5.cu")
# target_link_libraries(reduce_v5 MPI::MPI_CXX CUDA::cudart)

# add_executable(reduce_v6 "reduce_v6.cu")
# target_link_libraries(reduce_v6 MPI::MPI_CXX CUDA::cudart)

# add_executable(reduce_v7 "reduce_v7.cu")
# target_link_libraries(reduce_v7 MPI::MPI_CXX CUDA::cudart)

# if(CMAKE_BUILD_TYPE STREQUAL "Debug")
#     target_compile_options(reduce_v0 PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:-G>)
# endif()